### ISSUE TITLE
I followed all the steps in the installation guide, but I can not start any of the cores, and so I can't play anything.  What else do I need to do?  I made a topic about this earlier, and it was closed with the message, "You need to download the cores from the download section."  What download section?  Why does my system show a list of available cores if they haven't been downloaded?  I'm so confused.  PLEASE HELP!!!

### ISSUE THREAD

**Issue by abelogan** [Ruka-CFW/rk3128-cfw#67]

**Comment by fakemaria** [comment]
Its under releases,same place were you downloaded the cfw.
If you have more questions reach me on telegram. @fakemaria is my username/nick

**Comment by abelogan** [comment]
?Do you mean  having sdcard/.config/retroarch/cores on the sd card?  If so, I have that already..??

**Comment by fakemaria** [comment]
> ?Do you mean having sdcard/.config/retroarch/cores on the sd card? If so, I have that already..??

If you have the cores in the system,then your problem is config. You should go to settings and look for directories. And set the directory of the cores.
Im going to close the issue,as this is not an issue (the cfw is totally independent from retroarch). If you are lost and need a hand,reach me on Telegram :)
